version: '3.7'
services:
  frontend:
    build:
      context: .
      target: frontend
    volumes:
      - ./fe:/angular-app
      - /angular-app/node_modules
    command: ["build-dev"]
  backend:
    build:
      context: .
      target: backend
    ports:
      - 80:8080
    env_file:
      - .env
    volumes:
      - ./fe:/fe-dist/
      - ./app:/go-app
    command: ["--watch=./", "--bin-name=app"]
  db:
    image: postgres:10.7-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: docker