version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-node-browsers
    working_directory: ~/project

    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          command: |
            mkdir -p ~/tests/gotests
            cd ~/project/app
            go test -v ./... 2>&1 | go-junit-report > ~/tests/gotests/report.xml
      - store_test_results:
          path: ~/tests/gotests
#      - run:
#          command: |
#            cd ~/project/fe
#            npm install
#            ng test
  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
          docker login --username=_ --password=$KEROKU_TOKEN registry.heroku.com
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH