version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-node-browsers
    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "app/go.sum" }}
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          command: |
            mkdir -p ~/tests/gotests
            cd ~/project/app
            go test -v ./... 2>&1 | go-junit-report > ~/tests/gotests/report.xml
      - save_cache:
          key: go-mod-v1-{{ checksum "app/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: ~/tests/gotests
#      - run:
#          command: |
#            cd ~/project/fe
#            npm install
#            ng test
  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
              curl https://cli-assets.heroku.com/install.sh | sh
              docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
              docker login --username=$HEROKU_EMAIL --password=$HEROKU_TOKEN registry.heroku.com
              docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
              heroku container:release --app $HEROKU_APP_NAME web

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: heroku
